service: api-boilerplate

frameworkVersion: "3"

custom:
  prefix: ${self:service}-${opt:stage, self:provider.stage}

layers:
  deps:
    name: ${self:custom.prefix}-deps
    path: ./deps-layer
    package:
      patterns:
       - './nodejs/node_modules/**'
       - '!./nodejs/node_modules/@aws-sdk/**'

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  region: us-east-1
  apiGateway:
    minimumCompressionSize: 1024
  runtime: nodejs18.x
functions:
  server:
    handler: .build/server.handler
    layers:
      - !Ref DepsLambdaLayer
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - '!./**'
    - ".build/**"
